apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::234259793095:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::234259793095:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-OIS9PMF4FPR
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-12-22T05:55:20Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2020-12-22T05:55:20Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:mapRoles: {}
    manager: kubectl-patch
    operation: Update
    time: "2020-12-22T06:16:45Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "5035"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2ce2fb8c-c1a6-4b66-9d1f-99036284d1b2
